# Explore Dataset

In [1]:
# Open pickle and view dataframe
import pandas as pd
import pickle

data_path = '240125_aragorn_video.pkl'

with open(data_path, 'rb') as f:
    data = pickle.load(f)

data

,date,session_num,subject,trial_num,block,condition,correct,error,error_type,behavioral_code_markers,...,video_e3v831b,markers_e3v831b,video_e3v8360,markers_e3v8360,video_e3v83ad,markers_e3v83ad,video_e3v83d6,markers_e3v83d6,pupil_diff,pupil_window_nan
0,240125,0,aragorn,1,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,"[[-2932.6962817747017, -763.6627354312983, -31...",None,"[[-2124.5830038599915, 881.5857585314411, -459...",None,"[[-3156.3738179878096, 1069.1226300083727, -22...",None,"[[-797.0304119544913, -953.3025034743737, 1512...",None,264.662205,"[6412.0, 6413.0, 6413.0, 6413.0, 6413.0, 6409...."
1,240125,0,aragorn,2,1,1,0,1,3,"[9, 100, 101, 102, 103, 113, 18]",...,None,None,None,None,None,None,None,None,NaN,NaN
2,240125,0,aragorn,3,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,NaN,"[6047.0, 6047.0, 6060.0, 6060.0, 6056.0, 6056...."
3,240125,0,aragorn,4,1,1,0,1,4,"[9, 100, 101, 102, 103, 104, 113, 18]",...,None,None,None,None,None,None,None,None,NaN,NaN
4,240125,0,aragorn,5,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,222.589468,"[6352.0, 6349.0, 6349.0, 6349.0, 6349.0, 6346...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,240125,0,aragorn,636,4,2,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,977.872000,"[6776.0, 6776.0, 6776.0, 6776.0, 6776.0, 6776...."
636,240125,0,aragorn,637,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,843.441000,"[6447.0, 6447.0, 6447.0, 6447.0, 6447.0, 6447...."
637,240125,0,aragorn,638,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,761.846000,"[6027.0, 6027.0, 6027.0, 6036.0, 6036.0, 6039...."
638,240125,0,aragorn,639,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,-286.993000,"[6755.0, 6755.0, 6755.0, 6755.0, 6749.0, 6749...."
639,240125,0,aragorn,640,1,1,1,0,0,"[9, 100, 101, 102, 103, 104, 105, 106, 107, 10...",...,None,None,None,None,None,None,None,None,32.031000,"[5895.0, 5895.0, 5894.0, 5894.0, 5894.0, 5894...."